apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: default

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    application: event-exporter
  name: event-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      application: event-exporter
  template:
    metadata:
      labels:
        application: event-exporter
      annotations:
        kubernetes-log-watcher/scalyr-parser: '[{"container": "event-exporter", "parser": "event-exporter"}]'
    spec:
      serviceAccountName: operator
      containers:
      - name: event-exporter
        image: "{{{IMAGE}}}"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi

